### PR TITLE
chore(deps): upgrade ember-resource and refactor

### PR DESCRIPTION
**Pull request by derrabauke**
Another idea for the ugly `timeout` calls?

### CODE REVIEW

**Review by winged — APPROVED** [review]

**Comment by czosel** [comment]
Did you try `await settled();` instead of the timeout? (I know, eslint says it's not needed)

**Comment by derrabauke** [comment]
> Did you try `await settled();` instead of the timeout? (I know, eslint says it's not needed)

Yes, I did. But the `settled` was resolved before the task returned it's results. So this seems to be no option.

**Comment by czosel** [comment]
maybe @velrest or @anehx can give some insights on the `timeout` issue, potentially also after merging this? :wink:

**Pull request merged**
