### PR TITLE
chore: update to ember v4

### PR DESCRIPTION
**Pull request by velrest**
BREAKING CHANGE:
- Ember.js v3.28 or above
- Ember CLI v3.28 or above
- Node.js v14 or above

### CODE REVIEW

**Comment by velrest** [comment]
Currently putting this on-hold since all template files throw the following error:
```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-emeis]) in ember-emeis/components/acl-wizzard/select-card.js

/home/jonas/projects/ember-emeis/ember-emeis/components/acl-wizzard/select-card.js: Class constructor SetTransform cannot be invoked without 'new'TypeError: /home/jonas/projects/ember-emeis/ember-emeis/components/acl-wizzard/select-card.js: Class constructor SetTransform cannot be invoked without 'new'
    at preprocess (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:12848:28)
    at normalize (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:13493:15)
    at precompileJSON (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:6120:47)
    at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:6157:31)
    at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:19423:37)
    at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-cli-htmlbars/lib/utils.js:222:12)
    at insertCompiledTemplate (/home/jonas/projects/ember-emeis/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:50:42)
    at PluginPass.CallExpression (/home/jonas/projects/ember-emeis/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:142:21)
    at newFn (/home/jonas/projects/ember-emeis/node_modules/@babel/traverse/lib/visitors.js:159:21)
    at NodePath._call (/home/jonas/projects/ember-emeis/node_modules/@babel/traverse/lib/path/context.js:46:20)


Stack Trace and Error Report: /tmp/error.dump.55f1244da272e467d1af8ba6f0af82bb.log
```

**Comment by velrest** [comment]
> Currently putting this on-hold since all template files throw the following error:
> 
> ```
> Build Error (broccoli-persistent-filter:Babel > [Babel: ember-emeis]) in ember-emeis/components/acl-wizzard/select-card.js
> 
> /home/jonas/projects/ember-emeis/ember-emeis/components/acl-wizzard/select-card.js: Class constructor SetTransform cannot be invoked without 'new'TypeError: /home/jonas/projects/ember-emeis/ember-emeis/components/acl-wizzard/select-card.js: Class constructor SetTransform cannot be invoked without 'new'
>     at preprocess (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:12848:28)
>     at normalize (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:13493:15)
>     at precompileJSON (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:6120:47)
>     at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:6157:31)
>     at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-source/dist/ember-template-compiler.js:19423:37)
>     at precompile (/home/jonas/projects/ember-emeis/node_modules/ember-cli-htmlbars/lib/utils.js:222:12)
>     at insertCompiledTemplate (/home/jonas/projects/ember-emeis/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:50:42)
>     at PluginPass.CallExpression (/home/jonas/projects/ember-emeis/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:142:21)
>     at newFn (/home/jonas/projects/ember-emeis/node_modules/@babel/traverse/lib/visitors.js:159:21)
>     at NodePath._call (/home/jonas/projects/ember-emeis/node_modules/@babel/traverse/lib/path/context.js:46:20)
> 
> 
> Stack Trace and Error Report: /tmp/error.dump.55f1244da272e467d1af8ba6f0af82bb.log
> ```
> 
> I already tried:
> 
> * Updating all the dependencies
> * Debugging `ember-template-compiler` with no success
> * `npx yarn-deduplicate --packages ember-cli-htmlbars` as mentioned in [Breaks In Ember v4 DockYard/ember-maybe-in-element#47](https://github.com/DockYard/ember-maybe-in-element/issues/47)
> * `package.json` resolution for `ember-cli-handlebars` to `^6.1.1`
> 
> Help would be appreciated!
> 
> Related issues:
> 
> * [Class constructor SetTransform cannot be invoked without 'new' lifeart/ember-ref-bucket#23](https://github.com/lifeart/ember-ref-bucket/issues/23)
> * [Breaks In Ember v4 DockYard/ember-maybe-in-element#47](https://github.com/DockYard/ember-maybe-in-element/issues/47)

I resolved this issue.
Due to `SetTransform` beeing so generic i had a hard time to understand, which addon this came from and i thought this was a generic ember build class. Turns out after a `rg SetTransform` that `ember-simple-set-helper` still used the oldstyle class version of  [`registerPlugin`](https://deprecations.emberjs.com/v3.x/#toc_template-compiler-registerPlugin). Since this addon is deprecated anyway i replaced it with `ember-set-helper`.

**Comment by velrest** [comment]
Putting this on hold for now. There are still a lot of issues with the tests.

**Comment by derrabauke** [comment]
> Putting this on hold for now. There are still a lot of issues with the tests.

Can we push this together some time this week?

**Comment by derrabauke** [comment]
This needs `ensure-safe-component` wrapper or a direct component import ([more future safe](https://mainmatter.com/blog/2022/03/17/dynamic-components-embroider/))

https://github.com/projectcaluma/ember-emeis/blob/7ac04b3478237a1e89d37479bdd8fc3282def0e5/addon/components/relationship-select.hbs#L8

**Comment by velrest** [comment]
`ember-data@4.12` not working because of issue with embroider.
Results in `Uncaught Error: Could not find module `@ember-data/store` imported from `(require)`
`.

**Comment by derrabauke** [comment]
> `ember-data@4.12` not working because of issue with embroider. Results in `` Uncaught Error: Could not find module `@ember-data/store` imported from `(require)` ``.

Honestly, I've no idea what's going wrong here. Tried a couple of things but nothing seems to work.

I think we have two options here:
1. disable the `release` test scenario for now
2. downgrade ember-data 

Don't know if @anehx knows what could help us here. :shrug:

**Comment by derrabauke** [comment]
Btw: I think the `addon/routes/index.js` file needs some refactoring as of [ember v5](https://deprecations.emberjs.com/v3.x#toc_routing-transition-methods):
```js
import Route from "@ember/routing/route";
import { inject as service } from "@ember/service";

export default class IndexRoute extends Route {
  @service hostRouter;

  beforeModel() {
    this.hostRouter.transitionTo("users");
  }
}
```

**Comment by velrest** [comment]
> Btw: I think the `addon/routes/index.js` file needs some refactoring as of [ember v5](https://deprecations.emberjs.com/v3.x#toc_routing-transition-methods):
> 
> ```js
> import Route from "@ember/routing/route";
> import { inject as service } from "@ember/service";
> 
> export default class IndexRoute extends Route {
>   @service hostRouter;
> 
>   beforeModel() {
>     this.hostRouter.transitionTo("users");
>   }
> }
> `

What do you mean? We are using the `hostRouter` `transitionTo` here.

**Comment by derrabauke** [comment]
> > Btw: I think the `addon/routes/index.js` file needs some refactoring as of [ember v5](https://deprecations.emberjs.com/v3.x#toc_routing-transition-methods):
> > ```js
> > import Route from "@ember/routing/route";
> > import { inject as service } from "@ember/service";
> > 
> > export default class IndexRoute extends Route {
> >   @service hostRouter;
> > 
> >   beforeModel() {
> >     this.hostRouter.transitionTo("users");
> >   }
> > }
> > `
> > ```
> 
> What do you mean? We are using the `hostRouter` `transitionTo` here.

Sorry for confusing you. The code I've pasted was already refactored. The [original](https://github.com/projectcaluma/ember-emeis/blob/main/addon/routes/index.js) is not touched yet and should become the quoted code. :)

**Review by derrabauke — APPROVED** [review]
nice job! :sparkles:

**Pull request merged**
